language: cpp

jobs:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-10
          packages:
            - clang-10
            - ocl-icd-opencl-dev
            - opencl-headers
            - lcov
      env:
        - COMPILER=clang++-10

    - os: osx
      osx_image: xcode12.5
      env:
        - COMPILER=clang++
      cache:
        ccache: true
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                   ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lcov ccache                      ; fi
    - BUILD_DEBUG=1 make clean

script:
    - BUILD_COVERAGE=1 make all

after_success:
    # Run test
    - ./bin/clunittests
    # Creating report
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
