version: ~> 1.0
language: cpp

cache:
  - ccache

jobs:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - ppa:llvm-toolchain-focal-10
          packages:
            - clang-10
            - ocl-icd-opencl-dev
            - opencl-headers
            - lcov
            - ccache
      env:
        - COMPILER=clang++-10

    - os: osx
      osx_image: xcode12.5
      addons:
        homebrew:
          packages:
            - lcov
            - ccache
          update: true
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      env:
        - COMPILER=clang++

before_script:
    - BUILD_DEBUG=1 make clean

script:
    - BUILD_COVERAGE=1 make all

after_success:
    # Run test
    - ./bin/clunittests
    # Creating report
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' '*/usr/include/*' --output-file coverage.info
    - lcov --list coverage.info
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
