version: 1.0.{build}

image: Visual Studio 2019

skip_commits:
  # Builds just testing something on Travis CI don't need to be
  # done on AppVeyor
  message: /\[Travis\]|\[AppVeyor\]|\[LGTM\]|\[GitPod\]|\[CodeCov\]/
  # Dont build, if only documentation or was changed
  files:
    - '**/*.md'
    - '**/*.yml'
only_commits:
  message: /build/

environment:
  matrix:
    - PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

configuration:
  - Release

cache:
  - cuda_10.1.105_418.96_win10.exe -> appveyor.yml

before_build:
  - if "%PLATFORM%" == "x64" if not exist cuda_10.1.105_418.96_win10.exe appveyor DownloadFile https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.96_win10.exe -FileName cuda_10.1.105_418.96_win10.exe
  - if "%PLATFORM%" == "x64" cuda_10.1.105_418.96_win10.exe -s nvcc_10.1 cudart_10.1 curand_10.1 curand_dev_10.1 npp_10.1 npp_dev_10.1 nvml_dev_10.1 nvrtc_10.1 nvrtc_dev_10.1 visual_studio_integration_10.1
  - if "%PLATFORM%" == "x64" set CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.1
  - if "%PLATFORM%" == "x64" set PATH=%CUDA_PATH%\bin;%PATH%
  - if "%PLATFORM%" == "x64" set MSBUILDEXTENSIONS=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\extras\visual_studio_integration\MSBuildExtensions
  - if "%PLATFORM%" == "x64" set BUILDCUSTUMIZATIONS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations
  - echo %PLATFORM%
  - echo %CONFIGURATION%
  - echo %CUDA_PATH%
  - copy "%MSBUILDEXTENSIONS%\*" "%BUILDCUSTUMIZATIONS%"

build:
  verbosity: normal
  project: $(APPVEYOR_BUILD_FOLDER)\BitCrack.sln
